name: Spellcheck

on: [push, pull_request]

jobs:
  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: Install Dependencies
        run: |
          python -m pip install 'mkdocs-spellcheck[symspellpy]'
      - name: Check Spelling
        uses: TheGiraffe3/mkdocs-spellcheck@v1.0.0
        with:
          #backends:  # the backends you want to use
          symspellpy: 1  # as strings
          # known_words can also be a list of words
          #known_words: [known words]
          # ignore words in <code> tags
          ignore_code: yes
          # minimum length of words to consider
          min_length: 2
          # maximum number of capital letters in a word
          max_capital: 1
          # keep unicode characters
          allow_unicode: no
          # skip files entirely (supports Unix shell-style wildcards)
          #skip_files:
          #- file.md
          # whether to only check in strict mode
          strict_only: yes
